#
# Automatically tag a merge with master, or build a new image from the tag.
#
# Secrets required:
#  * `GCP_PROJECT_ID` - Google Cloud Project ID
#  * `GCP_SA_KEY` - JSON service account key
#

name: Release

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "README.md"

env:
  REGISTRY: europe-docker.pkg.dev
  REPO_PATH: invopop/apps

jobs:
  tag-build-publish:
    name: Tag, Build, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0" # make sure we get all commits!

      - name: Get repo details
        run: |
          echo "COMMIT_TYPE=$(echo $GITHUB_REF | cut -d / -f 2)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d / -f 2-)" >> $GITHUB_ENV
          echo "REPO_VERSION=$(echo $GITHUB_REF | cut -d / -f 3-)" >> $GITHUB_ENV

      - name: Bump version and push tag
        id: bump
        if: env.COMMIT_TYPE != 'tags'
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: true

      - name: Set Version from Semver Tag
        if: env.COMMIT_TYPE != 'tags'
        run: |
          echo "REPO_VERSION=${{ steps.bump.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker Credentials
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build
        run: |
          docker build -t ${{ env.REPO_NAME }} \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg REPO_VERSION=${{ env.REPO_VERSION }} \
            --build-arg GITHUB_REF="$GITHUB_REF" . \
            --build-arg GITHUB_USER="${{ secrets.GO_MOD_USER }}" \
            --build-arg GITHUB_PASS="${{ secrets.GO_MOD_PASS }}"

      - name: Tag Image
        run: |
          docker image tag ${{ env.REPO_NAME }} ${{ env.REGISTRY }}/${{ env.REPO_PATH }}/${{ env.REPO_NAME }}:${{ env.REPO_VERSION }}

      - name: Tag Latest Main Release
        if: env.COMMIT_TYPE != 'tags'
        run: |
          docker image tag ${{ env.REPO_NAME }} ${{ env.REGISTRY }}/${{ env.REPO_PATH }}/${{ env.REPO_NAME }}:${GITHUB_REF##*/}-${{ env.REPO_VERSION }}-$(date +'%Y%m%dT%H%M')
          docker image tag ${{ env.REPO_NAME }} ${{ env.REGISTRY }}/${{ env.REPO_PATH }}/${{ env.REPO_NAME }}:latest

      - name: Publish
        run: |
          docker image push --all-tags ${{ env.REGISTRY }}/${{ env.REPO_PATH }}/${{ env.REPO_NAME }}
